### ISSUE TITLE
Add presidio-anonymizer

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/modern-data-platform-stack#1085]
```yaml
  presidio-anonymizer:
    image: mcr.microsoft.com/presidio-anonymizer:latest
    container_name: anonymizer
    ports:
      - "5001:3000"
```
