### ISSUE TITLE
Add google/cadvisor to stack

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/modern-data-platform-stack#55]
cAdvisor (Container Advisor) provides container users an understanding of the resource usage and performance characteristics of their running containers.

Use the following snippet:

```
  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - lan
    restart: always
```

An example for how to integrate cAdvisor with Prometheus and Grafana can be found here: <https://github.com/stefanprodan/dockprom>
