### ISSUE TITLE
cheatsheet steps for update to latest version without loose data

### ISSUE THREAD

**Issue by johnfelipe** [TrivadisPF/modern-data-platform-stack#562]
Can u explain how can update actual stack to latest version, with all his functions, but without loose data already in cassandra, airflow and all other services already initialized

**Comment by johnfelipe** [comment]
i do this steps

```
      platys:
          platform-name: 'demo-platform'
          platform-stack: 'trivadis/platys-modern-data-platform'
          #platform-stack-version: '1.15.0'
          platform-stack-version: '1.16.0-preview'
          structure: 'flat'
```
next

```
platys gen

docker-compose up -d

```
is any steps for do it correclty?
