### ISSUE TITLE
Add owl-shop

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/modern-data-platform-stack#768]
<https://github.com/cloudhut/owl-shop>

```
  owl-shop:
    image: quay.io/cloudhut/owl-shop:latest
    #platform: 'linux/amd64'
    environment:
      - SHOP_KAFKA_BROKERS=redpanda:9092
      - SHOP_KAFKA_TOPICREPLICATIONFACTOR=1
      - SHOP_TRAFFIC_INTERVAL_RATE=1
      - SHOP_TRAFFIC_INTERVAL_DURATION=0.1s
    depends_on:
      - redpanda
```
