### ISSUE TITLE
Add LDN Inbox for Notification from Dataverse

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/modern-data-platform-stack#917]
<https://github.com/seanwiseman/coar-notify-inbox>

**Comment by gschmutz** [comment]
```
  ldn-inbox:
    container_name: ldn-inbox
    hostname: ldn-inbox
    image: dragasteff/coar-notify-inbox
    ports:
      - 8080:8080   
    environment:
      MONGO_DB_URI: mongodb://mongo-1:27017
      ON_RECEIVE_NOTIFICATION_WEBHOOK_URL: ""
      ALLOWED_ADMIN_ORIGINS: '["*"]'
      ALLOWED_ORIGINS: '["*"]'
    restart: no 
```
