### ISSUE TITLE
Add Polaris

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/modern-data-platform-stack#951]
<https://github.com/apache/polaris/blob/main/docker-compose.yml>

```yaml
  polaris:
    container_name: polaris
    healthcheck:
      interval: 10s
      retries: 5
      test: [CMD, curl, "http://localhost:8182/healthcheck"]
      timeout: 10s
    image: "datacatering/polaris:${POLARIS_VERSION:-1.0.0}"
    ports:
      - "8181:8181"
      - "8182:8182"
 ```
