### ISSUE TITLE
Integrate support for building and publishing docker images to a docker registry

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/modern-data-platform-stack#980]
```yml
  platys-docker-deployer-dbt:
    image: docker
    container_name: platys-docker-deployer-dbt
    hostname: platys-docker-deployer-dbt
    environment:
      DOCKER_REGISTRY: localhost:5020
    volumes:
      - ./data-transfer:/data-transfer
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      ./data-transfer/dbt/build-and-push-docker-images.sh
```
